Add permissions to GH actions.
Additionally removed writing the status for coverage.
It wasn't working properly on forks.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -6,6 +6,10 @@ on:
   pull_request:
     branches: master
 
+permissions:
+  contents: read
+  metadata: read
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -35,19 +39,10 @@ jobs:
         go test -v -coverpkg=./... -coverprofile=cov.out ./...
         go tool cover -html=cov.out -o coverage.html
         COV=$(go tool cover -func=cov.out | awk '/total/ { gsub("%", "", $3); print $3 }')
-        (( $(echo "${COV} > ${MIN_COV}" | bc -l) )) && STATE=success || STATE=failure
-        echo "::set-output name=COV::${COV}% (Required ${MIN_COV}%)"
-        echo "::set-output name=STATE::${STATE}"
+        echo "Total coverage: ${COV} (Required ${MIN_COV})"
+        (( $(echo "${COV} > ${MIN_COV}" | bc -l) )) && echo "Min coverage passed" || exit 1
       env:
         MIN_COV: 60
-
-    - uses: Sibz/github-status-action@v1
-      with: 
-        authToken: ${{secrets.GITHUB_TOKEN}}
-        description: '${{steps.coverage.outputs.COV}}'
-        context: 'Coverage'
-        state: '${{steps.coverage.outputs.STATE}}'
-        sha: ${{github.event.pull_request.head.sha || github.sha}}
 
     - uses: actions/upload-artifact@v2
       with:
